import 'modules/admin-lte/plugins/jQueryUI/jquery-ui.min' 
import 'modules/admin-lte/plugins/fastclick/fastclick' 
import 'modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min' 
import 'modules/admin-lte/dist/js/app.min'

import 'modules/font-awesome/css/font-awesome.min.css' 
import 'modules/ionicons/dist/css/ionicons.min.css' 
import 'modules/admin-lte/bootstrap/css/bootstrap.min.css' 
import 'modules/admin-lte/dist/css/AdminLTE.min.css' 
import 'modules/admin-lte/dist/css/skins/_all-skins.min.css' 
import 'modules/admin-lte/plugins/iCheck/flat/blue.css'

import 'modules/react-awesome-selector/dist/style.css'

import './custom.css'
import './responsive/utilities.css'
import './responsive/global.css'
import './responsive/global.js'
import './responsive/dashboard.css'
import './responsive/participanteindividual.css'
import './responsive/beneficiario.css'
import './responsive/sensibilidade.css'
import './responsive/usuario.css'
import './responsive/sobre.css'
import './responsive/renda.css'
